In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("../data/Customer Call List.xlsx")
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

#### Removendo valores duplicados

In [5]:
df[df.duplicated()]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [ ]:
df = df.drop_duplicates()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

#### Removendo coluna desnecesária

In [ ]:
df = df.drop(columns = "Not_Useful_Column")
df

#### Remove espaços em branco e outros caracteres

In [ ]:
df["Last_Name"] = df["Last_Name"].str.strip("123._/") # Argumento opcional
df

#### Padronizando valores categóricos

In [ ]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')

df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

#### Lidando com valores faltantes

In [ ]:
"""
É necessário avaliar se apenas remover é o suficiente.
Se o volume de nulos for muito alto, essa não é uma boa opção.
"""

df=df.fillna('')
df

#### Atualizando índices

In [ ]:
df = df.reset_index(drop=True)
df

#### N-Gramas

#### TF-IDF